/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.destin.tp9;

import id.destin.tp9.scenes.HomeScene;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application{
    @Override
    public void start(Stage stage) {
        stage.setTitle("My Apps");

        
        VBox root = new VBox();
        Scene scene = new Scene(root, 640, 480);
        stage.setScene(scene);
        stage.show();
        
        HomeScene homeScene = new HomeScene(stage);
        homeScene.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
